CREATE DATABASE IF NOT EXISTS caffe_camillo_colombi CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE caffe_camillo_colombi;
CREATE TABLE IF NOT EXISTS users(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(160) NOT NULL UNIQUE,phone VARCHAR(30),password_hash VARCHAR(255) NOT NULL,
 role ENUM('customer','operator','admin') NOT NULL DEFAULT 'customer',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX(role)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS addresses(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,label VARCHAR(60) DEFAULT 'Principal',street VARCHAR(160) NOT NULL,number VARCHAR(20) NOT NULL,complement VARCHAR(80),neighborhood VARCHAR(100),city VARCHAR(100) NOT NULL,state CHAR(2) NOT NULL,zip_code VARCHAR(12) NOT NULL,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,INDEX(user_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS origins(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL UNIQUE,slug VARCHAR(120) NOT NULL UNIQUE,description TEXT NOT NULL,image_url TEXT) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS roasts(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(50) NOT NULL UNIQUE,level TINYINT UNSIGNED NOT NULL,description VARCHAR(255) NOT NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS grindings(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(60) NOT NULL UNIQUE,slug VARCHAR(70) NOT NULL UNIQUE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS essences(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(60) NOT NULL UNIQUE,slug VARCHAR(70) NOT NULL UNIQUE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS categories(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(80) NOT NULL UNIQUE,slug VARCHAR(90) NOT NULL UNIQUE,description VARCHAR(255),active TINYINT(1) NOT NULL DEFAULT 1) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS products(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,category_id INT UNSIGNED NOT NULL,origin_id INT UNSIGNED NOT NULL,roast_id INT UNSIGNED NOT NULL,essence_id INT UNSIGNED NULL,
 name VARCHAR(140) NOT NULL,slug VARCHAR(160) NOT NULL UNIQUE,description TEXT NOT NULL,story TEXT NOT NULL,sensory_notes VARCHAR(255) NOT NULL,
 bean_type ENUM('arabica','conilon','mixed') NOT NULL,base_price DECIMAL(10,2) NOT NULL,available TINYINT(1) NOT NULL DEFAULT 1,featured TINYINT(1) NOT NULL DEFAULT 0,
 image_url TEXT,image_origin_url TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(category_id) REFERENCES categories(id),FOREIGN KEY(origin_id) REFERENCES origins(id),FOREIGN KEY(roast_id) REFERENCES roasts(id),FOREIGN KEY(essence_id) REFERENCES essences(id) ON DELETE SET NULL,
 CHECK(base_price>=0),INDEX(category_id),INDEX(roast_id),INDEX(origin_id),INDEX(bean_type),INDEX(available)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS product_variants(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,product_id INT UNSIGNED NOT NULL,grinding_id INT UNSIGNED NOT NULL,weight_grams SMALLINT UNSIGNED NOT NULL,price DECIMAL(10,2) NOT NULL,stock INT NOT NULL DEFAULT 0,available TINYINT(1) NOT NULL DEFAULT 1,
 UNIQUE(product_id,grinding_id,weight_grams),FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE,FOREIGN KEY(grinding_id) REFERENCES grindings(id),CHECK(weight_grams IN(250,500)),CHECK(price>=0),CHECK(stock>=0),INDEX(product_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS inventory_movements(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,variant_id INT UNSIGNED NOT NULL,type ENUM('in','out','adjustment') NOT NULL,quantity INT NOT NULL,reason VARCHAR(180) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(variant_id) REFERENCES product_variants(id) ON DELETE CASCADE,INDEX(variant_id,created_at)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS orders(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NULL,customer_name VARCHAR(120) NOT NULL,customer_email VARCHAR(160) NOT NULL,customer_phone VARCHAR(30) NOT NULL,
 fulfillment ENUM('delivery','pickup') NOT NULL DEFAULT 'delivery',address_text VARCHAR(500),subtotal DECIMAL(10,2) NOT NULL,shipping DECIMAL(10,2) NOT NULL DEFAULT 0,total DECIMAL(10,2) NOT NULL,
 payment_method ENUM('pix','credit_card') NOT NULL,payment_status ENUM('pending','confirmed','declined') NOT NULL DEFAULT 'pending',status ENUM('received','payment_confirmed','preparing','shipped','delivered','cancelled') NOT NULL DEFAULT 'received',notes VARCHAR(500),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,INDEX(user_id),INDEX(status),INDEX(payment_status),INDEX(created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS order_items(
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id INT UNSIGNED NOT NULL,variant_id INT UNSIGNED NOT NULL,product_id INT UNSIGNED NOT NULL,product_name VARCHAR(140) NOT NULL,variant_label VARCHAR(120) NOT NULL,quantity INT UNSIGNED NOT NULL,unit_price DECIMAL(10,2) NOT NULL,subtotal DECIMAL(10,2) NOT NULL,
 FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,FOREIGN KEY(variant_id) REFERENCES product_variants(id),FOREIGN KEY(product_id) REFERENCES products(id),CHECK(quantity>0),INDEX(order_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS order_status_history(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id INT UNSIGNED NOT NULL,status VARCHAR(40) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,INDEX(order_id,created_at)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS stock_notifications(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,product_id INT UNSIGNED NOT NULL,name VARCHAR(120),email VARCHAR(160) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,notified_at TIMESTAMP NULL,UNIQUE(product_id,email),FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS club_levels(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(60) NOT NULL UNIQUE,min_points INT UNSIGNED NOT NULL,discount_percent DECIMAL(5,2) NOT NULL DEFAULT 0,benefit VARCHAR(255) NOT NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS club_memberships(user_id INT UNSIGNED PRIMARY KEY,level_id INT UNSIGNED NOT NULL,points INT UNSIGNED NOT NULL DEFAULT 0,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(level_id) REFERENCES club_levels(id)) ENGINE=InnoDB;
