USE caffe_camillo_colombi;
INSERT IGNORE INTO categories(name,slug,description) VALUES('Cafés em pacote','cafes','Cafés artesanais Caffè Camillo Colombi.');
INSERT IGNORE INTO origins(name,slug,description,image_url) VALUES
('São Gabriel da Palha','sao-gabriel-da-palha','Origem apresentada pelo projeto como uma das raízes dos cafés da marca. Conteúdo institucional demonstrativo.','https://upload.wikimedia.org/wikipedia/commons/0/0c/Coffee_plantation_in_Brazil.jpg'),
('Domingos Martins','domingos-martins','Origem apresentada pelo projeto como uma das raízes dos cafés da marca. Conteúdo institucional demonstrativo.','https://upload.wikimedia.org/wikipedia/commons/0/0c/Coffee_plantation_in_Brazil.jpg');
INSERT IGNORE INTO roasts(name,level,description) VALUES('Torra fraca',1,'Mais delicada e luminosa.'),('Torra média',2,'Equilíbrio entre doçura, corpo e aroma.'),('Torra forte',3,'Mais intensa, encorpada e persistente.');
INSERT IGNORE INTO grindings(name,slug) VALUES('Fina','fina'),('Média','media'),('Grossa','grossa'),('Moka / italiana','moka');
INSERT IGNORE INTO essences(name,slug) VALUES('Tradicional','tradicional'),('Cacau','cacau'),('Chocolate','chocolate'),('Laranja','laranja');
INSERT IGNORE INTO club_levels(name,min_points,discount_percent,benefit) VALUES('Caffè',0,0,'Acesso ao Camillo Club.'),('Espresso',100,5,'5% de desconto em campanhas participantes.'),('Barista',300,8,'8% de desconto e brindes selecionados.'),('Maestro',700,12,'12% de desconto e acesso antecipado a edições especiais.');
INSERT IGNORE INTO products(category_id,origin_id,roast_id,essence_id,name,slug,description,story,sensory_notes,bean_type,base_price,featured,image_url,image_origin_url)
SELECT c.id,o.id,r.id,e.id,'Camillo Origem','camillo-origem','Um café artesanal pensado para quem quer começar pela essência da casa.','Este lote é apresentado como uma homenagem às origens escolhidas para o Caffè Camillo Colombi. O texto é demonstrativo e pode ser substituído pela história real da propriedade quando fornecida pela marca.','Chocolate, castanhas, caramelo','arabica',34.90,1,'/assets/images/package-arabica.svg',o.image_url FROM categories c,origins o,roasts r,essences e WHERE c.slug='cafes' AND o.slug='sao-gabriel-da-palha' AND r.name='Torra média' AND e.slug='tradicional' LIMIT 1;
INSERT IGNORE INTO products(category_id,origin_id,roast_id,essence_id,name,slug,description,story,sensory_notes,bean_type,base_price,featured,image_url,image_origin_url)
SELECT c.id,o.id,r.id,e.id,'Camillo Intenso','camillo-intenso','Torra forte para uma xícara de presença marcante.','Um perfil construído para valorizar corpo e intensidade. A origem e a narrativa exibidas aqui são demonstrativas até que a equipe forneça o texto oficial do lote.','Cacau, caramelo queimado, especiarias','conilon',49.90,1,'/assets/images/package-conilon.svg',o.image_url FROM categories c,origins o,roasts r,essences e WHERE c.slug='cafes' AND o.slug='domingos-martins' AND r.name='Torra forte' AND e.slug='tradicional' LIMIT 1;
INSERT IGNORE INTO products(category_id,origin_id,roast_id,essence_id,name,slug,description,story,sensory_notes,bean_type,base_price,featured,image_url,image_origin_url)
SELECT c.id,o.id,r.id,e.id,'Camillo Cacau','camillo-cacau','Edição especial com perfil aromático de cacau.','Uma edição especial pensada para unir café e uma sensação achocolatada. O texto é conceitual e deve ser validado pela marca antes da publicação comercial.','Cacau, chocolate amargo, noz','mixed',64.90,1,'/assets/images/package-cacau.svg',o.image_url FROM categories c,origins o,roasts r,essences e WHERE c.slug='cafes' AND o.slug='sao-gabriel-da-palha' AND r.name='Torra média' AND e.slug='cacau' LIMIT 1;
INSERT IGNORE INTO product_variants(product_id,grinding_id,weight_grams,price,stock) SELECT p.id,g.id,w.weight,ROUND(p.base_price + (CASE WHEN p.bean_type='arabica' THEN 0 WHEN p.bean_type='mixed' THEN 15 ELSE 30 END) + CASE WHEN w.weight=500 THEN 20 ELSE 0 END + CASE WHEN g.slug='moka' THEN 3 ELSE 0 END,2),CASE WHEN w.weight=250 THEN 18 ELSE 10 END FROM products p CROSS JOIN grindings g CROSS JOIN (SELECT 250 weight UNION ALL SELECT 500) w;
