-- Official catalog. INSERT OR IGNORE preserves existing merchant customizations.
PRAGMA foreign_keys = ON;
INSERT OR IGNORE INTO categories (id,name,slug,description,active) VALUES
(1,'Cafés em saco','cafes-em-saco','Linha principal de cafés embalados.',1);

INSERT OR IGNORE INTO origins (id,name,slug,city,state,description) VALUES
(1,'São Gabriel da Palha','sao-gabriel-da-palha','São Gabriel da Palha','ES','Origem capixaba ligada à tradição do Conilon.'),
(2,'Domingos Martins','domingos-martins','Domingos Martins','ES','Região serrana capixaba associada a cafés Arábica.');

INSERT OR IGNORE INTO roast_levels (id,name,slug,description,sort_order) VALUES
(1,'Torra Clara','clara','Mais brilho e percepção de acidez.',1),
(2,'Torra Média','media','Equilíbrio entre doçura, corpo e aroma.',2),
(3,'Torra Escura','escura','Maior intensidade e notas de torra.',3);

INSERT OR IGNORE INTO grind_types (id,name,slug,description,sort_order) VALUES
(1,'Grãos inteiros','graos-inteiros','Para moer imediatamente antes do preparo.',1),
(2,'Extra fina','extra-fina','Indicada para preparos que pedem moagem muito fina.',2),
(3,'Fina / Espresso','fina-espresso','Para espresso doméstico compatível.',3),
(4,'Moka italiana','moka-italiana','Ajustada para cafeteira Moka.',4),
(5,'Média','media','Indicada para coadores e métodos filtrados.',5),
(6,'Média-grossa','media-grossa','Boa para Clever e alguns métodos de infusão.',6),
(7,'Grossa / Prensa francesa','grossa-prensa','Para prensa francesa.',7);

INSERT OR IGNORE INTO aromas (id,name,slug) VALUES
(1,'Cacau','cacau'),(2,'Chocolate','chocolate'),(3,'Laranja','laranja');


INSERT OR IGNORE INTO categories (name,slug,description) VALUES ('Bebidas','bebidas','Cafés preparados e especialidades italianas.');
UPDATE products SET active=0 WHERE slug IN ('camillo-origine','camillo-montagna','camillo-famiglia','camillo-intenso','camillo-dolce','camillo-reserva','camillo-cacao','camillo-arancia','camillo-cioccolato');
INSERT OR IGNORE INTO products (category_id,slug,name,short_description,description,coffee_type,origin_id,roast_level_id,sensory_notes,brew_suggestion,featured,image_key,product_kind) SELECT c.id,'caffe-arabica','Caffè Arábica','Doçura natural e equilíbrio das montanhas capixabas.','Doçura natural e equilíbrio das montanhas capixabas.','arabica',o.id,r.id,'caramelo, mel e frutas amarelas','Escolha a moagem adequada ao seu preparo.',1,'caffe-arabica','packaged' FROM categories c,origins o,roast_levels r WHERE c.slug='cafes-em-saco' AND o.slug='domingos-martins' AND r.slug='media';
INSERT OR IGNORE INTO product_variants (product_id,grind_type_id,sku,weight_g,price,stock,unit_type,label) SELECT p.id,g.id,'CCC-' || p.slug || '-250-' || g.slug,250,52,20,'weight','250 g · ' || g.name FROM products p,grind_types g WHERE p.slug='caffe-arabica' AND g.slug IN ('graos-inteiros','extra-fina','fina-espresso','moka-italiana','media','media-grossa','grossa-prensa');
INSERT OR IGNORE INTO product_variants (product_id,grind_type_id,sku,weight_g,price,stock,unit_type,label) SELECT p.id,g.id,'CCC-' || p.slug || '-500-' || g.slug,500,92.56,20,'weight','500 g · ' || g.name FROM products p,grind_types g WHERE p.slug='caffe-arabica' AND g.slug IN ('graos-inteiros','extra-fina','fina-espresso','moka-italiana','media','media-grossa','grossa-prensa');
INSERT OR IGNORE INTO product_variants (product_id,grind_type_id,sku,weight_g,price,stock,unit_type,label) SELECT p.id,g.id,'CCC-' || p.slug || '-1000-' || g.slug,1000,171.6,20,'weight','1000 g · ' || g.name FROM products p,grind_types g WHERE p.slug='caffe-arabica' AND g.slug IN ('graos-inteiros','extra-fina','fina-espresso','moka-italiana','media','media-grossa','grossa-prensa');
INSERT OR IGNORE INTO products (category_id,slug,name,short_description,description,coffee_type,origin_id,roast_level_id,sensory_notes,brew_suggestion,featured,image_key,product_kind) SELECT c.id,'caffe-conilon','Caffè Conilon','Corpo intenso e persistência do Conilon capixaba.','Corpo intenso e persistência do Conilon capixaba.','conilon',o.id,r.id,'nozes, melaço e notas de torra','Escolha a moagem adequada ao seu preparo.',1,'caffe-conilon','packaged' FROM categories c,origins o,roast_levels r WHERE c.slug='cafes-em-saco' AND o.slug='sao-gabriel-da-palha' AND r.slug='media';
INSERT OR IGNORE INTO product_variants (product_id,grind_type_id,sku,weight_g,price,stock,unit_type,label) SELECT p.id,g.id,'CCC-' || p.slug || '-250-' || g.slug,250,44,20,'weight','250 g · ' || g.name FROM products p,grind_types g WHERE p.slug='caffe-conilon' AND g.slug IN ('graos-inteiros','extra-fina','fina-espresso','moka-italiana','media','media-grossa','grossa-prensa');
INSERT OR IGNORE INTO product_variants (product_id,grind_type_id,sku,weight_g,price,stock,unit_type,label) SELECT p.id,g.id,'CCC-' || p.slug || '-500-' || g.slug,500,78.32,20,'weight','500 g · ' || g.name FROM products p,grind_types g WHERE p.slug='caffe-conilon' AND g.slug IN ('graos-inteiros','extra-fina','fina-espresso','moka-italiana','media','media-grossa','grossa-prensa');
INSERT OR IGNORE INTO product_variants (product_id,grind_type_id,sku,weight_g,price,stock,unit_type,label) SELECT p.id,g.id,'CCC-' || p.slug || '-1000-' || g.slug,1000,145.2,20,'weight','1000 g · ' || g.name FROM products p,grind_types g WHERE p.slug='caffe-conilon' AND g.slug IN ('graos-inteiros','extra-fina','fina-espresso','moka-italiana','media','media-grossa','grossa-prensa');
INSERT OR IGNORE INTO products (category_id,slug,name,short_description,description,coffee_type,origin_id,roast_level_id,sensory_notes,brew_suggestion,featured,image_key,product_kind) SELECT c.id,'blend-arabica-conilon','Blend Arábica + Conilon','Equilíbrio de Arábica de Domingos Martins e Conilon de São Gabriel da Palha.','Equilíbrio de Arábica de Domingos Martins e Conilon de São Gabriel da Palha.','blend',o.id,r.id,'castanhas e caramelo','Escolha a moagem adequada ao seu preparo.',1,'blend-arabica-conilon','packaged' FROM categories c,origins o,roast_levels r WHERE c.slug='cafes-em-saco' AND o.slug='domingos-martins' AND r.slug='media';
INSERT OR IGNORE INTO product_variants (product_id,grind_type_id,sku,weight_g,price,stock,unit_type,label) SELECT p.id,g.id,'CCC-' || p.slug || '-250-' || g.slug,250,49,20,'weight','250 g · ' || g.name FROM products p,grind_types g WHERE p.slug='blend-arabica-conilon' AND g.slug IN ('graos-inteiros','extra-fina','fina-espresso','moka-italiana','media','media-grossa','grossa-prensa');
INSERT OR IGNORE INTO product_variants (product_id,grind_type_id,sku,weight_g,price,stock,unit_type,label) SELECT p.id,g.id,'CCC-' || p.slug || '-500-' || g.slug,500,87.22,20,'weight','500 g · ' || g.name FROM products p,grind_types g WHERE p.slug='blend-arabica-conilon' AND g.slug IN ('graos-inteiros','extra-fina','fina-espresso','moka-italiana','media','media-grossa','grossa-prensa');
INSERT OR IGNORE INTO product_variants (product_id,grind_type_id,sku,weight_g,price,stock,unit_type,label) SELECT p.id,g.id,'CCC-' || p.slug || '-1000-' || g.slug,1000,161.7,20,'weight','1000 g · ' || g.name FROM products p,grind_types g WHERE p.slug='blend-arabica-conilon' AND g.slug IN ('graos-inteiros','extra-fina','fina-espresso','moka-italiana','media','media-grossa','grossa-prensa');
INSERT OR IGNORE INTO products (category_id,slug,name,short_description,description,coffee_type,origin_id,roast_level_id,sensory_notes,brew_suggestion,featured,image_key,product_kind) SELECT c.id,'caffe-arabica-cacau','Caffè Arábica com Cacau','Arábica com aromatização adicionada de cacau, distinta das notas naturais.','Arábica com aromatização adicionada de cacau, distinta das notas naturais.','arabica',o.id,r.id,'doçura natural da base Arábica','Escolha a moagem adequada ao seu preparo.',1,'caffe-arabica-cacau','packaged' FROM categories c,origins o,roast_levels r WHERE c.slug='cafes-em-saco' AND o.slug='domingos-martins' AND r.slug='media';
INSERT OR IGNORE INTO product_aromas (product_id,aroma_id) SELECT p.id,a.id FROM products p,aromas a WHERE p.slug='caffe-arabica-cacau' AND a.slug='cacau';
INSERT OR IGNORE INTO product_variants (product_id,grind_type_id,sku,weight_g,price,stock,unit_type,label) SELECT p.id,g.id,'CCC-' || p.slug || '-250-' || g.slug,250,59,20,'weight','250 g · ' || g.name FROM products p,grind_types g WHERE p.slug='caffe-arabica-cacau' AND g.slug IN ('graos-inteiros','extra-fina','fina-espresso','moka-italiana','media','media-grossa','grossa-prensa');
INSERT OR IGNORE INTO product_variants (product_id,grind_type_id,sku,weight_g,price,stock,unit_type,label) SELECT p.id,g.id,'CCC-' || p.slug || '-500-' || g.slug,500,105.02,20,'weight','500 g · ' || g.name FROM products p,grind_types g WHERE p.slug='caffe-arabica-cacau' AND g.slug IN ('graos-inteiros','extra-fina','fina-espresso','moka-italiana','media','media-grossa','grossa-prensa');
INSERT OR IGNORE INTO product_variants (product_id,grind_type_id,sku,weight_g,price,stock,unit_type,label) SELECT p.id,g.id,'CCC-' || p.slug || '-1000-' || g.slug,1000,194.7,20,'weight','1000 g · ' || g.name FROM products p,grind_types g WHERE p.slug='caffe-arabica-cacau' AND g.slug IN ('graos-inteiros','extra-fina','fina-espresso','moka-italiana','media','media-grossa','grossa-prensa');
INSERT OR IGNORE INTO products (category_id,slug,name,short_description,description,coffee_type,origin_id,roast_level_id,sensory_notes,brew_suggestion,featured,image_key,product_kind) SELECT c.id,'caffe-arabica-chocolate','Caffè Arábica com Chocolate','Arábica com aromatização adicionada de chocolate, distinta das notas naturais.','Arábica com aromatização adicionada de chocolate, distinta das notas naturais.','arabica',o.id,r.id,'doçura natural da base Arábica','Escolha a moagem adequada ao seu preparo.',1,'caffe-arabica-chocolate','packaged' FROM categories c,origins o,roast_levels r WHERE c.slug='cafes-em-saco' AND o.slug='domingos-martins' AND r.slug='media';
INSERT OR IGNORE INTO product_aromas (product_id,aroma_id) SELECT p.id,a.id FROM products p,aromas a WHERE p.slug='caffe-arabica-chocolate' AND a.slug='chocolate';
INSERT OR IGNORE INTO product_variants (product_id,grind_type_id,sku,weight_g,price,stock,unit_type,label) SELECT p.id,g.id,'CCC-' || p.slug || '-250-' || g.slug,250,59,20,'weight','250 g · ' || g.name FROM products p,grind_types g WHERE p.slug='caffe-arabica-chocolate' AND g.slug IN ('graos-inteiros','extra-fina','fina-espresso','moka-italiana','media','media-grossa','grossa-prensa');
INSERT OR IGNORE INTO product_variants (product_id,grind_type_id,sku,weight_g,price,stock,unit_type,label) SELECT p.id,g.id,'CCC-' || p.slug || '-500-' || g.slug,500,105.02,20,'weight','500 g · ' || g.name FROM products p,grind_types g WHERE p.slug='caffe-arabica-chocolate' AND g.slug IN ('graos-inteiros','extra-fina','fina-espresso','moka-italiana','media','media-grossa','grossa-prensa');
INSERT OR IGNORE INTO product_variants (product_id,grind_type_id,sku,weight_g,price,stock,unit_type,label) SELECT p.id,g.id,'CCC-' || p.slug || '-1000-' || g.slug,1000,194.7,20,'weight','1000 g · ' || g.name FROM products p,grind_types g WHERE p.slug='caffe-arabica-chocolate' AND g.slug IN ('graos-inteiros','extra-fina','fina-espresso','moka-italiana','media','media-grossa','grossa-prensa');
INSERT OR IGNORE INTO products (category_id,slug,name,short_description,description,coffee_type,origin_id,roast_level_id,sensory_notes,brew_suggestion,featured,image_key,product_kind) SELECT c.id,'caffe-arabica-laranja','Caffè Arábica com Laranja','Arábica com aromatização adicionada de laranja, distinta das notas naturais.','Arábica com aromatização adicionada de laranja, distinta das notas naturais.','arabica',o.id,r.id,'doçura natural da base Arábica','Escolha a moagem adequada ao seu preparo.',1,'caffe-arabica-laranja','packaged' FROM categories c,origins o,roast_levels r WHERE c.slug='cafes-em-saco' AND o.slug='domingos-martins' AND r.slug='media';
INSERT OR IGNORE INTO product_aromas (product_id,aroma_id) SELECT p.id,a.id FROM products p,aromas a WHERE p.slug='caffe-arabica-laranja' AND a.slug='laranja';
INSERT OR IGNORE INTO product_variants (product_id,grind_type_id,sku,weight_g,price,stock,unit_type,label) SELECT p.id,g.id,'CCC-' || p.slug || '-250-' || g.slug,250,62,20,'weight','250 g · ' || g.name FROM products p,grind_types g WHERE p.slug='caffe-arabica-laranja' AND g.slug IN ('graos-inteiros','extra-fina','fina-espresso','moka-italiana','media','media-grossa','grossa-prensa');
INSERT OR IGNORE INTO product_variants (product_id,grind_type_id,sku,weight_g,price,stock,unit_type,label) SELECT p.id,g.id,'CCC-' || p.slug || '-500-' || g.slug,500,110.36,20,'weight','500 g · ' || g.name FROM products p,grind_types g WHERE p.slug='caffe-arabica-laranja' AND g.slug IN ('graos-inteiros','extra-fina','fina-espresso','moka-italiana','media','media-grossa','grossa-prensa');
INSERT OR IGNORE INTO product_variants (product_id,grind_type_id,sku,weight_g,price,stock,unit_type,label) SELECT p.id,g.id,'CCC-' || p.slug || '-1000-' || g.slug,1000,204.6,20,'weight','1000 g · ' || g.name FROM products p,grind_types g WHERE p.slug='caffe-arabica-laranja' AND g.slug IN ('graos-inteiros','extra-fina','fina-espresso','moka-italiana','media','media-grossa','grossa-prensa');
INSERT OR IGNORE INTO products (category_id,slug,name,short_description,description,coffee_type,origin_id,roast_level_id,sensory_notes,brew_suggestion,featured,image_key,product_kind) SELECT c.id,'espresso','Espresso','Extração curta, crema e corpo marcante.','Extração curta, crema e corpo marcante.','arabica',o.id,r.id,'Perfil do café de base.','Preparado para servir.',0,'espresso','beverage' FROM categories c,origins o,roast_levels r WHERE c.slug='bebidas' AND o.slug='domingos-martins' AND r.slug='media';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-espresso-normal',8,30,'volume','30 ml',30 FROM products WHERE slug='espresso';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-espresso-grande',12,30,'volume','60 ml',60 FROM products WHERE slug='espresso';
INSERT OR IGNORE INTO products (category_id,slug,name,short_description,description,coffee_type,origin_id,roast_level_id,sensory_notes,brew_suggestion,featured,image_key,product_kind) SELECT c.id,'ristretto','Ristretto','Extração concentrada e intensa.','Extração concentrada e intensa.','arabica',o.id,r.id,'Perfil do café de base.','Preparado para servir.',0,'ristretto','beverage' FROM categories c,origins o,roast_levels r WHERE c.slug='bebidas' AND o.slug='domingos-martins' AND r.slug='media';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-ristretto-normal',8,30,'volume','30 ml',30 FROM products WHERE slug='ristretto';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-ristretto-grande',12,30,'volume','60 ml',60 FROM products WHERE slug='ristretto';
INSERT OR IGNORE INTO products (category_id,slug,name,short_description,description,coffee_type,origin_id,roast_level_id,sensory_notes,brew_suggestion,featured,image_key,product_kind) SELECT c.id,'lungo','Lungo','Extração alongada, leve e aromática.','Extração alongada, leve e aromática.','arabica',o.id,r.id,'Perfil do café de base.','Preparado para servir.',0,'lungo','beverage' FROM categories c,origins o,roast_levels r WHERE c.slug='bebidas' AND o.slug='domingos-martins' AND r.slug='media';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-lungo-normal',9,30,'volume','60 ml',60 FROM products WHERE slug='lungo';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-lungo-grande',13,30,'volume','120 ml',120 FROM products WHERE slug='lungo';
INSERT OR IGNORE INTO products (category_id,slug,name,short_description,description,coffee_type,origin_id,roast_level_id,sensory_notes,brew_suggestion,featured,image_key,product_kind) SELECT c.id,'macchiato','Macchiato','Espresso marcado com espuma de leite.','Espresso marcado com espuma de leite.','arabica',o.id,r.id,'Perfil do café de base.','Preparado para servir.',0,'macchiato','beverage' FROM categories c,origins o,roast_levels r WHERE c.slug='bebidas' AND o.slug='domingos-martins' AND r.slug='media';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-macchiato-normal',10,30,'volume','60 ml',60 FROM products WHERE slug='macchiato';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-macchiato-grande',14,30,'volume','120 ml',120 FROM products WHERE slug='macchiato';
INSERT OR IGNORE INTO products (category_id,slug,name,short_description,description,coffee_type,origin_id,roast_level_id,sensory_notes,brew_suggestion,featured,image_key,product_kind) SELECT c.id,'cappuccino','Cappuccino','Espresso, leite vaporizado e espuma cremosa.','Espresso, leite vaporizado e espuma cremosa.','arabica',o.id,r.id,'Perfil do café de base.','Preparado para servir.',0,'cappuccino','beverage' FROM categories c,origins o,roast_levels r WHERE c.slug='bebidas' AND o.slug='domingos-martins' AND r.slug='media';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-cappuccino-normal',14,30,'volume','180 ml',180 FROM products WHERE slug='cappuccino';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-cappuccino-grande',18,30,'volume','250 ml',250 FROM products WHERE slug='cappuccino';
INSERT OR IGNORE INTO products (category_id,slug,name,short_description,description,coffee_type,origin_id,roast_level_id,sensory_notes,brew_suggestion,featured,image_key,product_kind) SELECT c.id,'caffe-latte','Caffè Latte','Espresso com leite vaporizado e espuma delicada.','Espresso com leite vaporizado e espuma delicada.','arabica',o.id,r.id,'Perfil do café de base.','Preparado para servir.',0,'caffe-latte','beverage' FROM categories c,origins o,roast_levels r WHERE c.slug='bebidas' AND o.slug='domingos-martins' AND r.slug='media';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-caffe-latte-normal',14,30,'volume','180 ml',180 FROM products WHERE slug='caffe-latte';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-caffe-latte-grande',18,30,'volume','250 ml',250 FROM products WHERE slug='caffe-latte';
INSERT OR IGNORE INTO products (category_id,slug,name,short_description,description,coffee_type,origin_id,roast_level_id,sensory_notes,brew_suggestion,featured,image_key,product_kind) SELECT c.id,'affogato','Affogato','Espresso servido sobre sorvete.','Espresso servido sobre sorvete.','arabica',o.id,r.id,'Perfil do café de base.','Preparado para servir.',0,'affogato','beverage' FROM categories c,origins o,roast_levels r WHERE c.slug='bebidas' AND o.slug='domingos-martins' AND r.slug='media';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-affogato-normal',17,30,'unit','Normal',NULL FROM products WHERE slug='affogato';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-affogato-grande',21,30,'unit','Grande',NULL FROM products WHERE slug='affogato';
INSERT OR IGNORE INTO products (category_id,slug,name,short_description,description,coffee_type,origin_id,roast_level_id,sensory_notes,brew_suggestion,featured,image_key,product_kind) SELECT c.id,'marocchino','Marocchino','Espresso com cacau e espuma de leite.','Espresso com cacau e espuma de leite.','arabica',o.id,r.id,'Perfil do café de base.','Preparado para servir.',0,'marocchino','beverage' FROM categories c,origins o,roast_levels r WHERE c.slug='bebidas' AND o.slug='domingos-martins' AND r.slug='media';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-marocchino-normal',14,30,'volume','120 ml',120 FROM products WHERE slug='marocchino';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-marocchino-grande',18,30,'volume','180 ml',180 FROM products WHERE slug='marocchino';
INSERT OR IGNORE INTO products (category_id,slug,name,short_description,description,coffee_type,origin_id,roast_level_id,sensory_notes,brew_suggestion,featured,image_key,product_kind) SELECT c.id,'bicerin','Bicerin','Camadas de café, chocolate e creme.','Camadas de café, chocolate e creme.','arabica',o.id,r.id,'Perfil do café de base.','Preparado para servir.',0,'bicerin','beverage' FROM categories c,origins o,roast_levels r WHERE c.slug='bebidas' AND o.slug='domingos-martins' AND r.slug='media';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-bicerin-normal',18,30,'volume','180 ml',180 FROM products WHERE slug='bicerin';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-bicerin-grande',22,30,'volume','250 ml',250 FROM products WHERE slug='bicerin';
INSERT OR IGNORE INTO products (category_id,slug,name,short_description,description,coffee_type,origin_id,roast_level_id,sensory_notes,brew_suggestion,featured,image_key,product_kind) SELECT c.id,'caffe-corretto','Caffè Corretto','Espresso com um toque de destilado.','Espresso com um toque de destilado.','arabica',o.id,r.id,'Perfil do café de base.','Preparado para servir.',0,'caffe-corretto','beverage' FROM categories c,origins o,roast_levels r WHERE c.slug='bebidas' AND o.slug='domingos-martins' AND r.slug='media';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-caffe-corretto-normal',15,30,'volume','60 ml',60 FROM products WHERE slug='caffe-corretto';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-caffe-corretto-grande',19,30,'volume','120 ml',120 FROM products WHERE slug='caffe-corretto';
INSERT OR IGNORE INTO products (category_id,slug,name,short_description,description,coffee_type,origin_id,roast_level_id,sensory_notes,brew_suggestion,featured,image_key,product_kind) SELECT c.id,'shakerato','Shakerato','Café batido com gelo para uma textura leve.','Café batido com gelo para uma textura leve.','arabica',o.id,r.id,'Perfil do café de base.','Preparado para servir.',0,'shakerato','beverage' FROM categories c,origins o,roast_levels r WHERE c.slug='bebidas' AND o.slug='domingos-martins' AND r.slug='media';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-shakerato-normal',14,30,'volume','180 ml',180 FROM products WHERE slug='shakerato';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-shakerato-grande',18,30,'volume','250 ml',250 FROM products WHERE slug='shakerato';
INSERT OR IGNORE INTO products (category_id,slug,name,short_description,description,coffee_type,origin_id,roast_level_id,sensory_notes,brew_suggestion,featured,image_key,product_kind) SELECT c.id,'moka','Moka','Preparo tradicional na cafeteira italiana.','Preparo tradicional na cafeteira italiana.','arabica',o.id,r.id,'Perfil do café de base.','Preparado para servir.',0,'moka','beverage' FROM categories c,origins o,roast_levels r WHERE c.slug='bebidas' AND o.slug='domingos-martins' AND r.slug='media';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-moka-normal',10,30,'volume','60 ml',60 FROM products WHERE slug='moka';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-moka-grande',14,30,'volume','120 ml',120 FROM products WHERE slug='moka';
INSERT OR IGNORE INTO products (category_id,slug,name,short_description,description,coffee_type,origin_id,roast_level_id,sensory_notes,brew_suggestion,featured,image_key,product_kind) SELECT c.id,'caffe-freddo','Caffè Freddo','Café gelado, refrescante e equilibrado.','Café gelado, refrescante e equilibrado.','arabica',o.id,r.id,'Perfil do café de base.','Preparado para servir.',0,'caffe-freddo','beverage' FROM categories c,origins o,roast_levels r WHERE c.slug='bebidas' AND o.slug='domingos-martins' AND r.slug='media';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-caffe-freddo-normal',13,30,'volume','180 ml',180 FROM products WHERE slug='caffe-freddo';
INSERT OR IGNORE INTO product_variants (product_id,sku,price,stock,unit_type,label,volume_ml) SELECT id,'CCC-caffe-freddo-grande',17,30,'volume','250 ml',250 FROM products WHERE slug='caffe-freddo';
